### ISSUE TITLE
作者正在开发吗

### ISSUE THREAD

**Issue by CKopoer** [oxygen-dioxide/Zhihu-UWP#1]
加油！之前的uwp知乎已经彻底没法用了

**Comment by oxygen-dioxide** [comment]
并不是我开发，这里只是一个镜像站用来存放安装包。

**Comment by CKopoer** [comment]
现在正在开发中吗，是在码云的项目吗


 
---原始邮件---
发件人: "oxygen-dioxide"<notifications@github.com&gt;
发送时间: 2020年12月23日 16:50:25
收件人: "oxygen-dioxide/Zhihu-UWP"<Zhihu-UWP@noreply.github.com&gt;;
抄送: "CKopoer"<ckopoer@163.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [oxygen-dioxide/Zhihu-UWP] 作者正在开发吗 (#1)




 
并不是我开发，这里只是一个镜像站用来存放安装包。

**Comment by oxygen-dioxide** [comment]
知乎uwp不是开源软件，原作者被下架后就停止开发了，此后再没有人开发，gitee上也没有。
另外，关于这个仓库：存放的就是当时下架的知乎uwp安装包。这个uwp必须登录才能用，所以我一直用网页版，我自己都不知道它用不了了。
